INFO     tests.test_logout_functionality:test_logout_functionality.py:33 Выход из системы выполнен успешно.